// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
};

export type ShoppingListCreationDto = {
    name?: string;
};

export type ShoppingListDto = {
    id: Brand<string, 'ShoppingListId'>;
    name: string;
};

export type ShoppingListItemDto = {
    id?: string;
    name?: string;
};

export type ShoppingListWithItemsDto = {
    items?: Array<ShoppingListItemDto>;
    id: Brand<string, 'ShoppingListId'>;
    name: string;
};

export type GetShoppingListsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/shopping-list';
};

export type GetShoppingListsResponses = {
    /**
     * OK
     */
    200: Array<ShoppingListDto>;
};

export type GetShoppingListsResponse = GetShoppingListsResponses[keyof GetShoppingListsResponses];

export type CreateShoppingListData = {
    body: ShoppingListCreationDto;
    path?: never;
    query?: never;
    url: '/api/shopping-list';
};

export type CreateShoppingListResponses = {
    /**
     * OK
     */
    200: ShoppingListWithItemsDto;
};

export type CreateShoppingListResponse = CreateShoppingListResponses[keyof CreateShoppingListResponses];

export type DeleteApiShoppingListByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/shopping-list/{id}';
};

export type DeleteApiShoppingListByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetShoppingListData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/shopping-list/{id}';
};

export type GetShoppingListErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetShoppingListError = GetShoppingListErrors[keyof GetShoppingListErrors];

export type GetShoppingListResponses = {
    /**
     * OK
     */
    200: ShoppingListWithItemsDto;
};

export type GetShoppingListResponse = GetShoppingListResponses[keyof GetShoppingListResponses];

export type PutApiShoppingListByIdData = {
    body: string;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/shopping-list/{id}';
};

export type PutApiShoppingListByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}/var/home/dpeter99/Documents/Projects/Totum/projects/cellarium/cellarium-backend` | (string & {});
};